export PATH_TO_PROJECTS="/codetemp/goloniel"
# export AUTH_REPO_PREFIX="auth/"
# export AUTH_REPO_NAME="goloniel-auth"
export PATH_TO_AUTH_REPO="$PATH_TO_PROJECTS/auth/goloniel-auth"
export PATH_TO_SOCIAL_REPO="$PATH_TO_PROJECTS/social/goloniel-social"
export PATH_TO_BOT_REPO="$PATH_TO_PROJECTS/bot/goloniel-discord-bot"
export PATH_TO_KEYS="$PATH_TO_PROJECTS/compose/goloniel-compose/keys"
